### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by nitrag** [jbrt/aws-eks#1]
Thank you for your examples.

So how would CI/CD pipeplines work with this directory structure?

```bash
cd terraform/1-Create-EKS-Cluster
terraform apply -auto-approve

cd ../2-Helm-and-packages
terraform apply -auto-approve

...
```

Something like that?

**Comment by jbrt** [comment]
Hello,

You can use these into your pipeline by using these following commands (in directories 1 and 2):

- terraform init (to download all the needed modules/providers)
- terraform apply -auto-approve

You have to be aware of that points:

- If you plan to use these templates into a pipeline, you should configure a Terraform backend for saving the state. Specially if you run terraform in an ephemeral context (ex: docker). It's a **very important production best practice**.
- These templates works with version 0.11 of Terraform not version 0.12 (in 0.12 version you have a lot of syntax changes and no all modules are compatibles with 0.12 version yet)
- If you plan to destruct your infrastructure after usage, you can destroy it by only run the destruction command into the directory number 1 (but you have to destroy all your deployments/services before. If don't, the VPC won't be destroyed).

This template will continue to evolve, specially on the Helm part, because I have to do a lot of testing  with that tool that's new for me.

Feel free to give your feedback if you found something interesting/wrong.

Best regards

**Comment by nitrag** [comment]
Great thanks, I was a little confused about how the multiple directories play into each other. I also tried and failed to find a solution that will combine creating the cluster (1) and installing helm (2) in the same "go". Your resource has been great, thanks again!

**Comment by jbrt** [comment]
Hi again @nitrag,

To be honest, I've tried to do the same thing at the beginning (put all the code into one single step). 
But, it involves a lot of dependencies problems (specially with the HELM provider). 

Anyway, I believe it's better to do not try to do too much things with Terraform: I mean, if you create your whole infrastructure with a single template (which is possible), it will be hard to maintain during the time. Because when you change something, you could have dependencies problems. 

So, having multiple templates (one for VPC, one for EKS cluster, one for apps deployment) it's a better option when you're in production.

Best regards,
